env:
  browser: true
  es6: true
extends: airbnb-base
globals:
  Atomics: readable
  SharedArrayBuffer: readable
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {
  no-unused-vars: error,
  spaced-comment: off,
  no-trailing-spaces: off,
  linebreak-style: off,
  arrow-parens: off
}
