env:
  browser: true
  es6: true
extends: airbnb-base
globals:
  Atomics: readable
  SharedArrayBuffer: readable
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  no-unused-vars: off
  spaced-comment: off
  no-trailing-spaces: off
  linebreak-style: off
  arrow-parens: off
  object-curly-spacing: off
  no-mixed-operators: off
  no-param-reassign: off
  no-plusplus: off
  no-extend-native: off
  nonblock-statement-body-position: off
  curly: off
  no-restricted-globals: off
  no-alert: off
